create table if not exists public.academic_terms (
  id integer generated by default as identity primary key,
  academic_year text not null,
  semester text not null,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  closed_at timestamptz,
  constraint academic_terms_academic_year_check check (
    academic_year ~ '^[0-9]{4}-[0-9]{4}$'
    and substring(academic_year from 6 for 4)::integer =
      substring(academic_year from 1 for 4)::integer + 1
  ),
  constraint academic_terms_semester_check check (
    semester in ('1st Semester', '2nd Semester')
  ),
  constraint academic_terms_status_check check (
    status in ('draft', 'active', 'closed')
  ),
  constraint academic_terms_unique_term unique (academic_year, semester),
  constraint academic_terms_activation_timestamps_check check (
    (status <> 'active' or activated_at is not null)
    and (status <> 'closed' or closed_at is not null)
  )
);

create unique index if not exists academic_terms_one_active_idx
  on public.academic_terms ((status))
  where status = 'active';

create index if not exists academic_terms_status_idx
  on public.academic_terms (status);

create index if not exists academic_terms_order_idx
  on public.academic_terms (academic_year desc, semester);

create or replace function public.activate_academic_term(target_term_id integer)
returns public.academic_terms
language plpgsql
set search_path = public, pg_temp
as $$
declare
  activated_term public.academic_terms;
begin
  if target_term_id is null then
    raise exception 'Academic term is required.';
  end if;

  if not exists (
    select 1
    from public.academic_terms
    where id = target_term_id
      and status = 'draft'
  ) then
    raise exception 'Only draft academic terms can be activated.';
  end if;

  update public.academic_terms
  set
    status = 'closed',
    closed_at = coalesce(closed_at, now())
  where status = 'active';

  update public.academic_terms
  set
    status = 'active',
    activated_at = coalesce(activated_at, now()),
    closed_at = null
  where id = target_term_id
    and status = 'draft'
  returning * into activated_term;

  if activated_term.id is null then
    raise exception 'Academic term activation failed because the term is no longer draft.';
  end if;

  return activated_term;
end;
$$;

revoke all on function public.activate_academic_term(integer)
  from public, anon, authenticated;

alter table public.academic_terms enable row level security;

drop policy if exists "Academic terms are readable by app users"
  on public.academic_terms;

create policy "Academic terms are readable by app users"
  on public.academic_terms
  for select
  to anon, authenticated
  using (true);

grant select on table public.academic_terms to anon, authenticated;

notify pgrst, 'reload schema';
