BEGIN;

CREATE TABLE IF NOT EXISTS public.student_organization_terms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL,
  organization_id integer NOT NULL,
  academic_term_id integer NOT NULL,
  status text NOT NULL DEFAULT 'active',
  source text NOT NULL DEFAULT 'system',
  removed_by integer NULL,
  removed_at timestamptz NULL,
  removal_reason text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_status_check'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_status_check
      CHECK (status IN ('active', 'removed'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_source_check'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_source_check
      CHECK (source IN ('masterlist', 'manual', 'board_csv', 'student_setup', 'program_sync', 'system'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_removed_fields_check'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_removed_fields_check
      CHECK (
        (status = 'active' AND removed_by IS NULL AND removed_at IS NULL)
        OR
        (status = 'removed' AND removed_at IS NOT NULL)
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_student_fkey'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_student_fkey
      FOREIGN KEY (student_id)
      REFERENCES public.students(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_organization_fkey'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_organization_fkey
      FOREIGN KEY (organization_id)
      REFERENCES public.organizations(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_academic_term_fkey'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_academic_term_fkey
      FOREIGN KEY (academic_term_id)
      REFERENCES public.academic_terms(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_removed_by_fkey'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_removed_by_fkey
      FOREIGN KEY (removed_by)
      REFERENCES public.admin_users(id)
      ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'student_organization_terms_unique'
      AND conrelid = 'public.student_organization_terms'::regclass
  ) THEN
    ALTER TABLE public.student_organization_terms
      ADD CONSTRAINT student_organization_terms_unique
      UNIQUE (student_id, organization_id, academic_term_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS student_organization_terms_term_org_status_idx
  ON public.student_organization_terms (academic_term_id, organization_id, status);

CREATE INDEX IF NOT EXISTS student_organization_terms_student_term_idx
  ON public.student_organization_terms (student_id, academic_term_id);

ALTER TABLE public.student_organization_terms ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.student_organization_terms
  FROM PUBLIC, anon, authenticated;

REVOKE ALL ON TABLE public.student_organization_terms
  FROM service_role;

GRANT SELECT, INSERT, UPDATE ON TABLE public.student_organization_terms
  TO service_role;

REVOKE ALL ON SEQUENCE public.student_organization_terms_id_seq
  FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE public.student_organization_terms_id_seq
  FROM service_role;

GRANT USAGE, SELECT ON SEQUENCE public.student_organization_terms_id_seq
  TO service_role;

INSERT INTO public.student_organization_terms (
  student_id,
  organization_id,
  academic_term_id,
  status,
  source
)
SELECT
  so.student_id,
  so.organization_id,
  at.id,
  'active',
  'system'
FROM public.student_organizations so
JOIN public.academic_terms at
  ON at.status = 'active'
JOIN public.student_term_enrollments ste
  ON ste.student_id = so.student_id
 AND ste.academic_term_id = at.id
 AND ste.enrollment_status = 'enrolled'
ON CONFLICT (student_id, organization_id, academic_term_id) DO NOTHING;

COMMIT;
