create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint,
  action text not null,
  timestamp timestamptz default now()
);

alter table if exists public.audit_logs
  add column if not exists actor_name text,
  add column if not exists actor_role text,
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists entity_label text,
  add column if not exists organization_id bigint,
  add column if not exists organization_name text,
  add column if not exists status text default 'completed',
  add column if not exists metadata jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default now();

update public.audit_logs
set created_at = coalesce(created_at, timestamp, now())
where created_at is null;

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_organization_id_idx
  on public.audit_logs (organization_id);

create index if not exists audit_logs_actor_user_id_idx
  on public.audit_logs (user_id);

create index if not exists audit_logs_action_idx
  on public.audit_logs (action);

create index if not exists audit_logs_entity_type_idx
  on public.audit_logs (entity_type);

alter table if exists public.audit_logs enable row level security;

drop policy if exists "Audit logs readable by authenticated app users" on public.audit_logs;
drop policy if exists "Audit logs insertable by authenticated app users" on public.audit_logs;

create policy "Audit logs readable by authenticated app users"
on public.audit_logs
for select
to authenticated
using (true);

create policy "Audit logs insertable by authenticated app users"
on public.audit_logs
for insert
to authenticated
with check (true);
