alter table public.elections
  add column if not exists campaign_start timestamp,
  add column if not exists student_result_visibility text not null default 'hidden';

alter table public.organizations
  add column if not exists logo_url text;

alter table public.students
  add column if not exists photo_url text,
  add column if not exists precinct_code text,
  add column if not exists batch_code text;

alter table public.admin_users
  add column if not exists photo_url text;

alter table public.elections
  add column if not exists campaign_end timestamp,
  add column if not exists voting_access_mode text not null default 'anywhere',
  add column if not exists location_label text,
  add column if not exists geo_lat double precision,
  add column if not exists geo_lng double precision,
  add column if not exists geo_radius_meters integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'elections_student_result_visibility_check'
  ) then
    alter table public.elections
      add constraint elections_student_result_visibility_check
      check (student_result_visibility in ('hidden', 'realtime'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'elections_voting_access_mode_check'
  ) then
    alter table public.elections
      add constraint elections_voting_access_mode_check
      check (
        voting_access_mode in (
          'anywhere',
          'onsite_qr',
          'precinct_qr',
          'batch_qr',
          'location_range'
        )
      );
  end if;
end
$$;

alter table public.candidates
  add column if not exists platform text,
  add column if not exists credentials text,
  add column if not exists campaign_media_urls jsonb not null default '[]'::jsonb,
  add column if not exists campaign_materials jsonb not null default '[]'::jsonb;

create table if not exists public.officers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations (id) on delete cascade,
  student_id bigint references public.students (id) on delete set null,
  officer_name text,
  position_title text not null,
  term_label text,
  term_start date,
  term_end date,
  photo_url text,
  is_current boolean not null default true,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint officers_name_check check (
    student_id is not null or officer_name is not null
  )
);

create index if not exists officers_organization_id_idx
  on public.officers (organization_id);

create index if not exists officers_student_id_idx
  on public.officers (student_id);

create table if not exists public.election_access_tokens (
  id bigint generated by default as identity primary key,
  election_id bigint not null references public.elections (id) on delete cascade,
  token text not null unique,
  scope_type text not null default 'general',
  scope_value text,
  is_active boolean not null default true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint election_access_tokens_scope_type_check check (
    scope_type in ('general', 'precinct', 'batch')
  )
);

create index if not exists election_access_tokens_election_id_idx
  on public.election_access_tokens (election_id);
